import { TeacherStudentView, ClassInsight } from '../types';

export const OFFLINE_STUDENTS_DATA: TeacherStudentView[] = [
  {
    id: 'student-rahul-01',
    name: 'Rahul Kumar',
    grade: 7,
    avatar: '👦🏽',
    learningLevel: 'intermediate',
    overallProgress: 68,
    averageScore: 74,
    subjectProgress: { math: 65, science: 78, english: 70 },
    weakTopics: ['Fractions & Decimals', 'Algebra Basics & Equations'],
    strongTopics: ['Plant Biology & Photosynthesis', 'Human Body & Nutrition'],
    lastSync: '28 Sep 2026, 09:15 AM',
    lastActive: 'Today, 09:12 AM',
    needsSupport: true,
    learningSpeed: 'normal',
    recommendedIntervention: 'Reinforce fraction addition with visual fraction circles and roti analogies.',
  },
  {
    id: 'student-priya-02',
    name: 'Priya Sharma',
    grade: 7,
    avatar: '👧🏽',
    learningLevel: 'advanced',
    overallProgress: 88,
    averageScore: 91,
    subjectProgress: { math: 92, science: 89, english: 85 },
    weakTopics: ['Simple Machines (Pulleys)'],
    strongTopics: ['Algebra Basics & Equations', 'Geometry & Land Measurement', 'Plant Biology & Photosynthesis'],
    lastSync: '28 Sep 2026, 09:40 AM',
    lastActive: 'Today, 09:30 AM',
    needsSupport: false,
    learningSpeed: 'fast',
    recommendedIntervention: 'Ready for Grade 8 advanced algebra and science challenge modules.',
  },
  {
    id: 'student-anita-03',
    name: 'Anita Devi',
    grade: 7,
    avatar: '👧🏾',
    learningLevel: 'beginner',
    overallProgress: 52,
    averageScore: 56,
    subjectProgress: { math: 48, science: 55, english: 53 },
    weakTopics: ['Fractions & Decimals', 'Energy & Simple Machines', 'Parts of Speech'],
    strongTopics: ['Geometry & Land Measurement'],
    lastSync: '27 Sep 2026, 04:15 PM',
    lastActive: 'Yesterday',
    needsSupport: true,
    learningSpeed: 'slow',
    recommendedIntervention: 'Recommend small-group audio guidance and remedial fraction cards.',
  },
  {
    id: 'student-arun-04',
    name: 'Arun Patel',
    grade: 7,
    avatar: '👦🏾',
    learningLevel: 'intermediate',
    overallProgress: 76,
    averageScore: 79,
    subjectProgress: { math: 74, science: 82, english: 72 },
    weakTopics: ['Water Cycle & Rainwater Harvesting'],
    strongTopics: ['Algebra Basics & Equations', 'Simple Machines'],
    lastSync: '28 Sep 2026, 08:30 AM',
    lastActive: 'Today, 08:20 AM',
    needsSupport: false,
    learningSpeed: 'normal',
    recommendedIntervention: 'Performing well; assign science water conservation project.',
  },
  {
    id: 'student-sunita-05',
    name: 'Sunita Meena',
    grade: 7,
    avatar: '👧🏽',
    learningLevel: 'beginner',
    overallProgress: 58,
    averageScore: 61,
    subjectProgress: { math: 50, science: 64, english: 60 },
    weakTopics: ['Fractions & Decimals', 'Algebra Basics & Equations'],
    strongTopics: ['Human Body & Nutrition'],
    lastSync: '28 Sep 2026, 10:10 AM',
    lastActive: 'Today, 09:55 AM',
    needsSupport: true,
    learningSpeed: 'slow',
    recommendedIntervention: 'Visual manipulatives recommended for decimal place values.',
  },
];

export const OFFLINE_CLASS_INSIGHTS: any = {
  totalStudents: 5,
  activeToday: 4,
  averageAttendanceRate: 94,
  mostChallengingTopic: 'Fractions & Decimals (Math)',
  identifiedGapsSummary: [
    {
      topic: 'Fractions & Decimals',
      affectedStudentsCount: 3,
      remedialStrategy: 'Hands-on paper folding and village roti division activities.',
    },
    {
      topic: 'Algebra Basics & Equations',
      affectedStudentsCount: 2,
      remedialStrategy: 'Balance scale physical manipulatives (stones & boxes).',
    },
    {
      topic: 'Simple Machines & Pulleys',
      affectedStudentsCount: 2,
      remedialStrategy: 'Observe village water well pulley system during outdoor lab.',
    },
  ],
  recommendedTeacherAction:
    'Schedule a 20-minute small-group workshop on Fraction Addition using physical manipulatives before tomorrow morning solar sync.',
};
